#!/usr/bin/env bash
[[ " help checks:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | ps:help)
    help_content='    checks <app>, Show zero-downtime status
    checks:enable <app>, Enable zero-downtime checks
    checks:disable <app>, Disable zero-downtime checks'
    if [[ $1 = "ps:help" ]] ; then
        echo "$help_content" | sed "/^\s*$help_topic/!d" | sort | column -c2 -t -s,
    else
        echo "$help_content"
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
