#!/usr/bin/env bash
[[ " help shell:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | shell:help)
    help_contnet='    shell, Spawn dokku shell'
    if [[ $1 = "shell:help" ]] ; then
        echo "$help_content" | sed "/^\s*$help_topic/!d" | sort | column -c2 -t -s,
    else
        echo "$help_content"
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
